<a href="https://colab.research.google.com/github/T-Svitlichna/DTA_Python/blob/main/HomeWork/numpy_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [16]:
import numpy as np

# Твій код:
temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])

print(temps)
print(f'ndim: {temps.ndim}, shape: {temps.shape}, size: {temps.size}, dtype: {temps.dtype}')
print(f'min: {temps.min()}, max: {temps.max()}, mean: {temps.mean():.1f}')

[-5 -4  2 10 17 21 23 22 16  9  2 -3]
ndim: 1, shape: (12,), size: 12, dtype: int64
min: -5, max: 23, mean: 9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [17]:
# Твій код:
plan = np.full((3, 4), 50)
print("Plan_sales", "\n",plan)
print(f'ndim: {plan.ndim}, shape: {plan.shape}, size: {plan.size}, dtype: {plan.dtype}')

bonus = np.zeros((3, 4))
print(plan + bonus)

Plan_sales 
 [[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]
ndim: 2, shape: (3, 4), size: 12, dtype: int64
[[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [18]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
print("Продажі першого тижня (дні 1–7):", sales[:7].sum())
print("Продажі другого тижня (дні 8–14):", sales[7:14].sum())
print("Продажі у вихідні:", sales[[5,6,12,13]].sum())
print("Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...):", sales[::2].sum())
print("Масив у зворотному порядку:", sales[::-1])


Продажі першого тижня (дні 1–7): 3055
Продажі другого тижня (дні 8–14): 3180
Продажі у вихідні: 2445
Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...): 3140
Масив у зворотному порядку: [595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [19]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:
print("Оцінки Олени:", grades[0])
print("Оцінки всіх студентів з 3-го предмету:", grades[:, 2])
print("Оцінки Максима та Ані з предметів 2–4:", grades[1:3, 1:4])
print("Оцінка останнього студента з останнього предмету:", grades[-1, -1])

Оцінки Олени: [85 72 91 78 88]
Оцінки всіх студентів з 3-го предмету: [91 74 82 68]
Оцінки Максима та Ані з предметів 2–4: [[88 74 95]
 [65 82 70]]
Оцінка останнього студента з останнього предмету: 79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [20]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:
print("Ціни у гривнях:", np.round(prices_usd * 41.5, 2))
print("Ціни з ПДВ:", np.round(prices_usd * 41.5 * 1.2, 2))
print("Мінімальна ціна з ПДВ:", np.round(prices_usd * 41.5 * 1.2, 2).min())
print("Максимальна ціна з ПДВ:", np.round(prices_usd * 41.5 * 1.2, 2).max())
print("Середня ціна з ПДВ:", np.round(prices_usd * 41.5 * 1.2 ).mean().round(2))
print("Сума всіх товарів з ПДВ:", np.round(prices_usd * 41.5 * 1.2, 2).sum())


Ціни у гривнях: [ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]
Ціни з ПДВ: [ 796.3  2116.5   398.4  6225.   1680.75 3346.56  497.5 ]
Мінімальна ціна з ПДВ: 398.4
Максимальна ціна з ПДВ: 6225.0
Середня ціна з ПДВ: 2151.57
Сума всіх товарів з ПДВ: 15061.01


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [21]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:
tot_sum = quantity * cost_each
print("Загальна вартість кожного товару на складі:", tot_sum)
print("Загальна вартість всього складу:", tot_sum.sum())
print("Товар з найбільшою сумарною вартістю:", names[tot_sum.argmax()])# імя/назва/значення - виведеного індексу
print("Товар з найменшою сумарною вартістю:", names[tot_sum.argmin()])
print("Середня вартість одного найменування на складі:", tot_sum.mean().round(2))

Загальна вартість кожного товару на складі: [ 30000  81000  13500 171000  28500  24000  45000]
Загальна вартість всього складу: 393000
Товар з найбільшою сумарною вартістю: Монітор
Товар з найменшою сумарною вартістю: Зошит
Середня вартість одного найменування на складі: 56142.86


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [42]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:
mask = delivery_time <= 30
mask1 = delivery_time > 30
print("Вчасні замовлення:", delivery_time[mask])
print("Запізнілі замовлення:", delivery_time[mask1])
tot_order = delivery_time.size
print("Вчасні замовлення:", delivery_time[delivery_time <= 30].size)
print("Запізнілі замовлення:", delivery_time[delivery_time > 30].size)
print("Відсоток запізнілих замовлень:", round(delivery_time[mask1].size / tot_order * 100, 1), "%")
print("Середня затримка серед запізнілих замовлень:", round(delivery_time[mask].mean(), 1))

Вчасні замовлення: [22 28 19 27 24 26 18 29 23 20]
Запізнілі замовлення: [35 41 55 33 48 31 52 38 44 36]
Вчасні замовлення: 10
Запізнілі замовлення: 10
Відсоток запізнілих замовлень: 50.0 %
Середня затримка серед запізнілих замовлень: 23.6


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [23]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
day_more_than_mean = daily[daily > daily.mean()]
print("Дні з продажами вище середнього за місяць:", day_more_than_mean)
print("Кількість таких днів:", day_more_than_mean.size)
status = np.where(daily > daily.mean(), 'Гарний день', 'Звичайний день')
print("Перші 10 днів:")
print("-" * 35) # prosto pslochki
for i in range(10):
    print(f"День {i+1:2}: {daily[i]:4}  |  {status[i]}")
print("-" * 35)

Дні з продажами вище середнього за місяць: [535 800 714 566 558 472 763 761 869 443 591 513 485 559]
Кількість таких днів: 14
Перші 10 днів:
-----------------------------------
День  1:  202  |  Звичайний день
День  2:  535  |  Гарний день
День  3:  370  |  Звичайний день
День  4:  206  |  Звичайний день
День  5:  171  |  Звичайний день
День  6:  800  |  Гарний день
День  7:  120  |  Звичайний день
День  8:  714  |  Гарний день
День  9:  221  |  Звичайний день
День 10:  566  |  Гарний день
-----------------------------------


---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [24]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:
mat_new = hourly.reshape(6, 4)
print("Матриця 6×4:")
print(mat_new)
print("Сума продажів у кожному 4-годинному блоці (по рядках):", mat_new.sum(axis=1))
print("Відсортований 1D масив за зростанням:", np.sort(hourly))
print("Індекси годин відсортованих за зростанням продажів:", np.argsort(hourly))
print("Топ-3 найпродуктивніших години (їхні номери, рахуючи з 0):", np.argsort(hourly)[-3:]) # vzyv z kinza

Матриця 6×4:
[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]
Сума продажів у кожному 4-годинному блоці (по рядках): [ 28  66 235 240 257 112]
Відсортований 1D масив за зростанням: [ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]
Індекси годин відсортованих за зростанням продажів: [ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]
Топ-3 найпродуктивніших години (їхні номери, рахуючи з 0): [19 12 18]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [37]:
np.random.seed(99)
ages = np.random.randint(18, 66, size=50)
scores = np.round(np.random.normal(7, 1.5, size=50), 1)
scores = np.clip(scores, 1, 10)
print("Середній вік клієнтів:", ages.mean())
print("Середню оцінку задоволеності:", scores.mean().round(2))
print("Кількість клієнтів з оцінкою >= 8 («задоволені»):", (scores >= 8).sum())
print("Відсоток задоволених:", round((scores >= 8).mean() * 100, 1), "%")

Середній вік клієнтів: 41.8
Середню оцінку задоволеності: 6.87
Кількість клієнтів з оцінкою >= 8 («задоволені»): 10
Відсоток задоволених: 20.0 %


### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [25]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [26]:
# Твій код:
print("Загальнаlinguа виручка за 56 днів:", sales_56.sum())
print("Середньоденнаlinguа виручка:", round(sales_56.mean(), 2))
print("Мінімальний продаж", sales_56.min(),"Максимальний денний продаж:",  sales_56.max())
print("Стандартне відхилення (наскільки продажі «скачуть») на :", round(sales_56.std(),2))

Загальнаlinguа виручка за 56 днів: 31819
Середньоденнаlinguа виручка: 568.2
Мінімальний продаж 222 Максимальний денний продаж: 1072
Стандартне відхилення (наскільки продажі «скачуть») на : 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [34]:
# Твій код:
matrizza = sales_56.reshape(8, 7)
print("Матриця 8×7:")
print(matrizza)
print("Сума продажів кожного тижня:", matrizza.sum(axis=1))
print("Найкращий тиждень:", matrizza.sum(axis=1).argmax() + 1, "на суму:", matrizza.sum(axis=1).max())
print("Жень тижня в середньому найприбутковіший", matrizza.mean(axis=0).argmax)
print("Середньоденний max прибуток :", matrizza.mean(axis=1).round().max())

Матриця 8×7:
[[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]
Сума продажів кожного тижня: [4555 3921 3563 3546 5036 3300 4228 3670]
Найкращий тиждень: 5 на суму: 5036
Жень тижня в середньому найприбутковіший <built-in method argmax of numpy.ndarray object at 0x7de062dc7c30>
Середньоденний max прибуток : 719.0


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [41]:
# Твій код:


mask = matrizza < 400
mask1 = matrizza > 700
labels = np.where(matrizza < 400, 'Слабкий', np.where(matrizza > 700, 'Сильний', 'Нормальний'))
print("Кількість «слабких» днів:", matrizza[mask].size)
print("Кількість «сильних» днів:", matrizza[mask1].size)
print("Середня виручка у слабкі дні:", matrizza[mask].mean())
print("Середня виручка у сильних дні:", matrizza[mask1].mean())
print("Перші 14 днів:")
print("Перші 14 днів:")
print("-" * 35)
for i in range(8):
    print(f"День {i+1:2}:")
    for sale, label in zip(matrizza[i], labels[i]):
        print(f"   {sale:4}  |  {label}")
    print("-" * 35)


Кількість «слабких» днів: 12
Кількість «сильних» днів: 19
Середня виручка у слабкі дні: 302.0
Середня виручка у сильних дні: 785.1578947368421
Перші 14 днів:
Перші 14 днів:
-----------------------------------
День  1:
    706  |  Сильний
    739  |  Сильний
    748  |  Сильний
    646  |  Нормальний
    383  |  Слабкий
    556  |  Нормальний
    777  |  Сильний
-----------------------------------
День  2:
    427  |  Нормальний
    274  |  Слабкий
    522  |  Нормальний
    680  |  Нормальний
    708  |  Сильний
    465  |  Нормальний
    845  |  Сильний
-----------------------------------
День  3:
    447  |  Нормальний
    402  |  Нормальний
    551  |  Нормальний
    567  |  Нормальний
    723  |  Сильний
    404  |  Нормальний
    469  |  Нормальний
-----------------------------------
День  4:
    254  |  Слабкий
    314  |  Слабкий
    383  |  Слабкий
    754  |  Сильний
    297  |  Слабкий
    472  |  Нормальний
   1072  |  Сильний
-----------------------------------
День  5:
   

---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
